**Notice**

- 아래와 같이 **주석으로 구분된 곳에서 코드를 수정 및 작성** 해주세요

```python
    # ================================================================== #
    #         START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)        #
    # ================================================================== #
    #
    #                이 곳에서 코드를 수정 및 작성하시오.
    #
    # ================================================================== #
    #          END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)         #
    # ================================================================== #
```

> 코드를 작성할 때에는 잠시 비디오를 멈추고 혼자 충분히 고민해보며 작성해본 후, 다시 강의를 들어주세요.

# Pandas

## 통계

## 모듈 import

In [ ]:
from IPython.display import Image
import numpy as np
import pandas as pd
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

## 데이터셋 로드

In [ ]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

**컬럼(columns) 설명**

- survivied: 생존여부 (1: 생존, 0: 사망)
- pclass: 좌석 등급 (1등급, 2등급, 3등급)
- sex: 성별
- age: 나이
- sibsp: 형제 + 배우자 수
- parch: 부모 + 자녀 수
- fare: 좌석 요금
- embarked: 탑승 항구 (S, C, Q)
- class: pclass와 동일
- who: 남자(man), 여자(woman), 아이(child)
- adult_male: 성인 남자 여부
- deck: 데크 번호 (알파벳 + 숫자 혼용)
- embark_town: 탑승 항구 이름
- alive: 생존여부 (yes, no)
- alone: 혼자 탑승 여부

# 통계

**통계**는 데이터 분석에서 굉장히 **중요한 요소**이다.

데이터에 대한 통계 계산식을 Pandas 함수로 제공하기 때문에 어렵지 않게 통계 값을 산출할 수 있다.

## 1. describe() - 요약통계

전반적인 주요 통계를 확인할 수 있다.

기본 값으로 **수치형(Numerical) 컬럼**에 대한 통계표를 보여준다.

- **count**: 데이터 개수
- **mean**: 평균
- **std**: 표준편차
- **min**: 최솟값
- **max**: 최대값

In [ ]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

**문자열 컬럼에 대한 통계표**도 확인할 수 있다.

- **count**: 데이터 개수
- **unique**: 고유 데이터의 값 개수
- **top**: 가장 많이 출현한 데이터 개수
- **freq**: 가장 많이 출현한 데이터의 빈도수

In [ ]:
df.describe(include='object')

         sex embarked  who  embark_town alive
count    891      889  891          889   891
unique     2        3    3            3     2
top     male        S  man  Southampton    no
freq     577      644  537          644   549

## 2. count() - 개수

데이터의 개수를 구할 수 있다.

DataFrame 전체의 개수를 구하는 경우

In [ ]:
df.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

단일 column의 데이터 개수를 구하는 경우

In [ ]:
df['age'].count()

np.int64(714)

## 3. mean() - 평균

데이터의 **평균**을 구할 수 있다.

`age` 컬럼에 대한 평균

In [ ]:
df['age'].mean()

np.float64(29.69911764705882)

### Mean - 조건별 평균

성인 남성의 나이의 평균 구하기

In [ ]:
condition = (df['adult_male'] == True)
df.loc[condition, 'age'].mean()

np.float64(33.17312348668281)

다음 조건을 만족하는 승객의 **나이 평균**과 조건을 만족하는 **데이터의 개수**를 구해보자.

> `fare`를 30 이상 40 미만 지불한 승객
>
> `pclass`는 1등급

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# ================================================================== #
#         START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)        #
# ================================================================== #

data_count = ...

# ================================================================== #
#          END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)         #
# ================================================================== #
data_count

Ellipsis

In [ ]:
# ================================================================== #
#         START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)        #
# ================================================================== #

# 조건 필터링: fare가 30 이상 40 미만 & pclass가 1등급
filtered_data = df[(df["fare"] >= 30) & (df["fare"] < 40) & (df["pclass"] == 1)]

# 나이 평균 계산 (결측치 제외)
age_mean = filtered_data["age"].mean()

# 데이터 개수 계산
data_count = len(filtered_data)

# ================================================================== #
#          END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)         #
# ================================================================== #
data_count

28

`age` 컬럼의 데이터 개수 구하기

In [ ]:
# ================================================================== #
#         START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)        #
# ================================================================== #

age_count = ...

# ================================================================== #
#          END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)         #
# ================================================================== #
age_count

In [ ]:
# ================================================================== #
#         START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)        #
# ================================================================== #

age_count = filtered_data["age"].count()

# ================================================================== #
#          END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)         #
# ================================================================== #
age_count

np.int64(21)

`age`컬럼의 평균 구하기

In [ ]:
# ================================================================== #
#         START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)        #
# ================================================================== #

age_mean = ...

# ================================================================== #
#          END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)         #
# ================================================================== #
age_mean

In [ ]:
# ================================================================== #
#         START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)        #
# ================================================================== #

age_mean = filtered_data["age"].mean()

# ================================================================== #
#          END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)         #
# ================================================================== #
age_mean

np.float64(44.095238095238095)

### `skipna=True` 옵션

기술 통계 함수에서는 `skipna=True`가 **기본으로 설정** 되어 있다.

만약, `skipna=False`로 설정하게 된다면, **NaN 값이 있는 column은 NaN 값으로 출력** 된다.

In [ ]:
# skipna=False를 지정한 경우
df['age'].mean(skipna=False)

np.float64(nan)

In [ ]:
# skipna=True를 지정한 경우
df['age'].mean(skipna=True)

np.float64(29.69911764705882)

## 4. median() - 중앙값

데이터의 중앙 값을 출력 한다.

데이터를 **오름차순 정렬하여 중앙에 위치한 값**이다.

이상치(outlier)가 존재하는 경우, `mean()`보다 `median()`을 대표값으로 더 **선호**한다.

In [ ]:
pd.Series([1, 2, 3, 4, 5]).median()

3.0

In [ ]:
pd.Series([4, 5, 1, 2, 3]).median()

3.0

**짝수**개의 데이터가 있는 경우에는 **가운데 2개 중앙 데이터의 평균 값을 출력** 한다.

In [ ]:
pd.Series([1, 2, 3, 4, 5, 6]).median()

3.5

나이의 평균(mean)과 중앙값(median)은 약간의 **차이가 있음**을 확인할 수 있다.

In [ ]:
print(f"나이 평균: {df['age'].mean():.5f}\n나이 중앙값: {df['age'].median()}\n차이: {df['age'].mean() - df['age'].median():.5f}")

나이 평균: 29.69912
나이 중앙값: 28.0
차이: 1.69912

## 5. sum() - 합계

데이터의 **합계**이다. 문자열 column은 모든 데이터가 붙어서 출력될 수 있다.

In [ ]:
df.loc[:, ['age', 'fare']].sum()

age     21205.1700
fare    28693.9493
dtype: float64

단일 column에 대한 **합계 출력**

In [ ]:
df['fare'].sum()

np.float64(28693.9493)

## 6. cumsum() - 누적합, cumprod() - 누적곱

누적되는 합계를 구할 수 있다.

In [ ]:
df['age'].cumsum()

0         22.00
1         60.00
2         86.00
3        121.00
4        156.00
         ...
886    21128.17
887    21147.17
888         NaN
889    21173.17
890    21205.17
Name: age, Length: 891, dtype: float64

누적되는 곱도 구할 수 있으나, 일반적으로 **값이 너무 커지므로 잘 활용하지는 않는다.**

In [ ]:
df['age'].cumprod()

0            22.0
1           836.0
2         21736.0
3        760760.0
4      26626600.0
          ...
886           inf
887           inf
888           NaN
889           inf
890           inf
Name: age, Length: 891, dtype: float64

## 7. var() - 분산

$\large 분산 = \Huge\frac{\sum_{i=1}^{n}(X_{i} - \bar{X})^{2}}{n-1}$

$\large 평균 = \huge \bar{x}$

In [ ]:
# 평균
fare_mean = df['fare'].values.mean()
fare_mean

np.float64(32.204207968574636)

In [ ]:
# 분산
my_var = ((df['fare'].values - fare_mean) ** 2).sum() / (df['fare'].count() - 1)
my_var

np.float64(2469.436845743116)

다음과 같이 간단하게 분산을 구할 수 있다.

In [ ]:
df['fare'].var()

2469.436845743117

## 8. std() - 표준편차

$\large 표준편차 =\huge \sqrt{분산} = \sqrt{\frac{{}\sum_{i=1}^{n}(X_{i} - \bar{X})^{2}}{n-1}}$

분산(var)의 제곱근

In [ ]:
np.sqrt(df['fare'].var())

np.float64(49.693428597180905)

In [ ]:
df['fare'].std()

49.693428597180905

## 9. min() - 최소값, max() - 최대값

.min(), .max()를 붙여 간단하게 최대 최소 값을 구할 수 있다.

In [ ]:
# 최소값
df['age'].min()

0.42

In [ ]:
# 최대값
df['age'].max()

80.0

## 10. agg - aggregation: 통합 통계 적용 (복수의 통계 함수 적용)

.agg를 이용하여 여러개의 통계 함수를 적용할 수 있다.

단일 컬럼에 agg 적용

In [ ]:
df['age'].agg(['min', 'max', 'count', 'mean'])

min        0.420000
max       80.000000
count    714.000000
mean      29.699118
Name: age, dtype: float64

복수의 컬럼에 agg 적용

In [ ]:
df[['age', 'fare']].agg(['min', 'max', 'count', 'mean'])

              age        fare
min      0.420000    0.000000
max     80.000000  512.329200
count  714.000000  891.000000
mean    29.699118   32.204208

다이아몬드 데이터를 활용하여 다음의 문제를 풀어보자.

In [ ]:
diamond = sns.load_dataset('diamonds')
diamond

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

depth의 **최소값**을 구해보자.

In [ ]:
# ================================================================== #
#         START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)        #
# ================================================================== #

depth = ...

# ================================================================== #
#          END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)         #
# ================================================================== #
depth

`carat`에 대한 **평균**과 **분산**을 동시에 출력하세요

In [ ]:
# ================================================================== #
#         START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)        #
# ================================================================== #

agg = ...

# ================================================================== #
#          END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)         #
# ================================================================== #
agg

x, y에 대한 **합계**와 **표준편차**를 출력하세요

In [ ]:
# ================================================================== #
#         START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)        #
# ================================================================== #

agg = ...

# ================================================================== #
#          END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)         #
# ================================================================== #
agg

## 11. quantile() - 분위

**Quantile이란 주어진 데이터를 동등한 크기로 분할하는 지점**을 말한다

10%의 경우 0.1을, 80%의 경우 0.8을 대입하여 값을 구한다.

In [ ]:
# 10% quantile
df['age'].quantile(0.1)

np.float64(14.0)

In [ ]:
# 80% quantile
df['age'].quantile(0.8)

np.float64(41.0)

## 12. unique() - 고유값, nunique() - 고유값 개수

고유값과 고유값의 개수를 구하고자 할 때 사용한다.

**unique()**

In [ ]:
df['who'].unique()

array(['man', 'woman', 'child'], dtype=object)

**nunique()**: 고유값의 개수를 출력한다.

In [ ]:
df['who'].nunique()

3

## 13. mode() - 최빈값

최빈값은 **가장 많이 출현한 데이터**를 의미한다.

In [ ]:
df['who'].mode()

0    man
Name: who, dtype: object

카테고리형 데이터에도 적용 가능하다.

In [ ]:
df['deck'].mode()

0    C
Name: deck, dtype: category
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

펭귄 데이터를 활용하여 다음의 문제를 풀어보자

In [ ]:
penguin = sns.load_dataset('penguins')
penguin

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

`species` 컬럼의 **고유값**을 출력해보자

In [ ]:
# ================================================================== #
#         START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)        #
# ================================================================== #



# ================================================================== #
#          END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)         #
# ================================================================== #

`island` 컬럼의 **최빈값**을 출력해보자

In [ ]:
# ================================================================== #
#         START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)        #
# ================================================================== #



# ================================================================== #
#          END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)         #
# ================================================================== #

`body_mass_g` 컬럼의 10% 분위수 값(하위 10%)을 출력해보자

In [ ]:
# ================================================================== #
#         START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)        #
# ================================================================== #



# ================================================================== #
#          END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)         #
# ================================================================== #

`body_mass_g` 컬럼의 80% 분위수 값(상위 20%)을 출력해보자

In [ ]:
# ================================================================== #
#         START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)        #
# ================================================================== #



# ================================================================== #
#          END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)         #
# ================================================================== #

## 14. corr() - 상관관계

`corr()`로 컬럼(column)별 **상관관계**를 확인할 수 있다.

> **-1~1 사이의 범위**를 가진다.
>
> **-1에 가까울 수록 반비례** 관계, **1에 가까울수록 정비례** 관계를 의미한다.

corr함수는 숫자형 데이터에서만 작동하기 때문에, `numeric_only=True`를 붙여준다.

In [ ]:
df.corr(numeric_only=True)

,survived,pclass,age,sibsp,parch,fare,adult_male,alone
survived,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307,-0.557080,-0.203367
pclass,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500,0.094035,0.135207
age,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067,0.280328,0.198270
sibsp,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651,-0.253586,-0.584471
parch,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225,-0.349943,-0.583398
fare,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000,-0.182024,-0.271832
adult_male,-0.557080,0.094035,0.280328,-0.253586,-0.349943,-0.182024,1.000000,0.404744
alone,-0.203367,0.135207,0.198270,-0.584471,-0.583398,-0.271832,0.404744,1.000000

**특정 컬럼에 대한 상관관계**를 확인할 수 있다.

In [ ]:
df.corr(numeric_only=True)['survived']

survived      1.000000
pclass       -0.338481
age          -0.077221
sibsp        -0.035322
parch         0.081629
fare          0.257307
adult_male   -0.557080
alone        -0.203367
Name: survived, dtype: float64